title: SURE 2025
description: The Workshop on Software Understanding and Reverse Engineering
baseurl: ""
url: ""

permalink: pretty

home: /
copyright: SURE
indexing: true
favicon: assets/icons/favicon.ico

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/
  - map.md

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never


remote_theme: piazzai/jekyll-nagymaros 
