title: SURE
description: workshop
baseurl: ""
url: ""

permalink: pretty

home: /
copyright: Place Holder
indexing: true

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/
  - map.md
  - program.md

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never


remote_theme: piazzai/jekyll-nagymaros 
